#!/bin/sh
set -e

case "$1" in
    purge)
        test -d /etc/X11/fluxbox && rm -rf /etc/X11/fluxbox
    ;;
    remove)
        ;;
    *)
        ;;
esac


# Automatically added by dh_installmenu/13.23~mx23+1
inst=/etc/menu-methods/fluxbox
if [ "$1" = "remove" ] && [ -f "$inst" ]; then chmod a-x $inst ; fi
if [ -x "`command -v update-menus`" ] && [ -x "$DPKG_ROOT`command -v update-menus`" ]; then update-menus ; fi
# End automatically added section

