#!/bin/sh
#
#  fluxbox postinst
#
#  Shamelessly ripped off of Marcelo Magallon's script
#     by Brent Fulgham <bfulgham@debian.org>
#
# Ripped off blackbox's postinst, by Matt Hope <dopey@debian.org>
#
set -e

manager=/usr/bin/startfluxbox

add_wm_entry ()
{
    update-alternatives --install /usr/bin/x-window-manager \
        x-window-manager $manager 50 \
          --slave /usr/share/man/man1/x-window-manager.1.gz \
        x-window-manager.1.gz /usr/share/man/man1/fluxbox.1.gz
}

case "$1" in
    configure)
        add_wm_entry
    ;;

    abort-*)
        # how did we get here?  Force a non-zero exit code
        exit 1
    ;;

    *)
    ;;
esac

# Automatically added by dh_installmenu/13.23~mx23+1
inst=/etc/menu-methods/fluxbox
if [ -f $inst ]; then
	chmod a+x $inst
	if [ -x "`command -v update-menus`" ] && [ -x "$DPKG_ROOT`command -v update-menus`" ]; then
		update-menus
	fi
fi
# End automatically added section

